
# enable app support
APP=1
APP_STACKSIZE=300

VPATH += src/
PROJ_OBJ += Main.o InformationHandler.o CommandHandler.o SensorCommands.o MovementCommands.o MissionCommands.o

CRAZYFLIE_BASE=../
include $(CRAZYFLIE_BASE)/Makefile
